apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-dev-pv-01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/java-dev-pv-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-dev-pv-02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/java-dev-pv-02
