apiVersion: v1
kind: Service
metadata:
  name: resources-back-service
  namespace: k8s-java-dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 31080
  selector:
    app: resources-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-back-deployment
  namespace: k8s-java-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-back
  template:
    metadata: 
      name: resources-back
      labels:
        app: resources-back
    spec:
      containers:
      - name: microservice-intro-resource-service
        image: microservice-intro-resource-service
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        startupProbe:
          httpGet:
            path: /health/
            port: http
          failureThreshold: 30
          periodSeconds: 10              
        livenessProbe:
          httpGet:
            path: /health/
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15    
        readinessProbe:
          httpGet:
            path: /health/
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15    
        env:
          name: RESOURCES_DB_URL
          valueFrom:
            configMapKeyRef:
              name: k8s-java-dev-config
              key: resources.RESOURCES_DB_URL
          name: RESOURCES_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: k8s-java-dev-config
              key: resources.RESOURCES_DB_PORT
          name: SONGS_MS_URL
          valueFrom:
            configMapKeyRef:
              name: k8s-java-dev-config
              key: resources.SONGS_MS_URL
          name: SONGS_MS_PORT
          valueFrom:
            configMapKeyRef:
              name: k8s-java-dev-config
              key: resources.SONGS_MS_PORT
