apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-java-dev-songs-config
  namespace: {{ .Values.global.namespace }}
data:
  songs.SONGS_DB_URL: songs-service-db-postgres-service.k8s-java-dev.svc
  songs.SONGS_MS_PORT: "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: songs-service-db-init-config
  namespace: {{ .Values.global.namespace }}
data:
  init.sql: |
    create sequence songs_seq start with 1 increment by 50 ;

    create table songs ( id integer not null,
      resource_id integer not null unique,
      album varchar(255),
      artist varchar(255),
      length varchar(255),
      name varchar(255),
      year varchar(255),
      primary key (id)
    );
