apiVersion: v1
kind: Secret
metadata:
  name: k8s-java-dev-resources-secrets
  namespace: {{ .Values.global.namespace }}
data:
  resources.RESOURCE_DB_USER: cG9zdGdyZXM=
  resources.RESOURCE_DB_PASS: cG9zdGdyZXM=
