apiVersion: v1
kind: Pod
metadata:
  name: postgresql-db
  labels: 
    app: postgresql-db
spec:
  containers:
  - name: postgresql-db
    image: 'postgres:latest'
    imagePullPolicy: IfNotPresent
    ports:
      - name: postgresql-db
        containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: abc123 
