apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-service-db-init-config
  namespace: k8s-java-dev
data:
  init.sql: |
    ALTER USER postgres with encrypted password 'postgres';

    CREATE TABLE IF NOT EXISTS customers (
           customer_id bpchar NOT NULL,
           company_name character varying(40) NOT NULL,
           contact_name character varying(30),
           contact_title character varying(30),
           address character varying(60),
           city character varying(15),
           region character varying(15),
           postal_code character varying(10),
           country character varying(15),
           phone character varying(24),
           fax character varying(24)
     );

     INSERT INTO customers VALUES ('ALFKI', 'Alfreds Futterkiste', 'Maria Anders', 'Sales Representative', 'Obere Str. 57', 'Berlin', NULL, '12209', 'Germany', '030-0074321', '030-0076545');

---
apiVersion: v1
kind: Service
metadata:
  name: resources-service-db-postgres-service
  namespace: k8s-java-dev
  labels:
    app: resources-service-db
spec:
    clusterIP: None 
    ports:
      - port: 5432
        targetPort: resources-db
    selector:
      app: resources-service-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-service-db-postgres
  namespace: k8s-java-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-service-db
  template:
    metadata: 
      labels:
        app: resources-service-db
    spec:
      containers:
      - name: resources-service-db
        image: 'postgres:latest'
        imagePullPolicy: IfNotPresent
        ports:
          - name: resources-db
            containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: resources-service-db-postgresdata

          - mountPath: /docker-entrypoint-initdb.d
            name: resources-db-initdb
      volumes:
        - name: resources-db-initdb
          configMap:
            name: resources-service-db-init-config  
  volumeClaimTemplates:
  - metadata: 
      name: resources-service-db-postgresdata
      namespace: k8s-java-dev
    spec:
      storageClassName: manual
      resources:
        requests:
          storage: 2Gi
      accessModes:
      - ReadWriteOnce
