apiVersion: v1
kind: Service
metadata:
  name: resources-back-service
  namespace: k8s-java-dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 31080
  selector:
    app: resources-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-back-deployment
  namespace: k8s-java-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-back
  template:
    metadata: 
      name: resources-back
      labels:
        app: resources-back
    spec:
      containers:
      - name: microservice-intro-resource-service
        image: microservice-intro-resource-service
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        env: 
          - name: RESOURCES_DB_URL
            value: resources-service-db-postgres-service.k8s-java-dev.svc.cluster.local
          - name: SONGS_MS_URL
            value: songs-back-service.k8s-java-dev.svc.cluster.local
          - name: SONGS_MS_PORT
            value: "80"
          - name: RESOURCES_DB_PORT
            value: "5432" 
