apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-service-db-pvc
  namespace: k8s-java-dev
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:  
    requests:
      storage: 3Gi
