apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources-service-db-pvc
  namespace: k8s-java-dev
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: resources-service-db-postgres-service
  namespace: k8s-java-dev
  labels:
    app: resources-service-db
spec: 
    type: NodePort
    ports:
      - port: 5432
        targetPort: resources-db
        nodePort: 31432
    selector:
      app: resources-service-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-db-postgres
  namespace: k8s-java-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-service-db
  template:
    metadata: 
      labels:
        app: resources-service-db
    spec:
      containers:
      - name: resources-service-db
        image: 'postgres:latest'
        imagePullPolicy: IfNotPresent
        ports:
          - name: resources-db
            containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: resources-service-db-postgresdata
      volumes:
        - name: resources-service-db-postgresdata
          persistentVolumeClaim:
            claimName: resources-service-db-pvc
