apiVersion: v1
kind: Service
metadata:
  name: songs-service-db-postgres-service
  namespace: k8s-java-dev
  labels:
    app: songs-service-db
spec:
    clusterIP: None 
    ports:
      - port: 5432
        targetPort: songs-db
    selector:
      app: songs-service-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-service-db-postgres
  namespace: k8s-java-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-service-db
  minReadySeconds: 2
  template:
    metadata: 
      labels:
        app: songs-service-db
    spec:
      containers:
      - name: songs-service-db
        image: 'postgres:latest'
        imagePullPolicy: IfNotPresent
        ports:
          - name: songs-db
            containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: songs-db-postgresdata
  volumeClaimTemplates:
    - metadata: 
        name: songs-db-postgresdata
        namespace: k8s-java-dev
      spec: 
        storageClassName: manual
        resources:
          requests:
            storage: 2Gi
        accessModes:
        - ReadWriteOnce
